# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Item.destroy_all

# Vegetable
Item.create(name: "ADOBONG KANGKONG", misc: "MARKET PRICE", dish: "Vegetable", desc: "ongchoy - adobo")
Item.create(name: "ADOBONG SITAW", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "long beans - adobo")
Item.create(name: "AMPALAYA CON KARNE", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Bitter melon w/ beef")
Item.create(name: "AMPALAYA WITH EGG & SHRIMP", smallT: 27, mediumT: 50, largeT: 95, dish: "Vegetable". desc: "Bitter melon w/ shrimp & scrambled egg")
Item.create(name: "ASPARAGUS WITH SHRIMP", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Sesame shrimp & asparagus stir-fry")
Item.create(name: "BROCCOLI WITH BEEF", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Stir-fried beef & broccoli")
Item.create(name: "CHINESE BROCCOLI WITH BEEF", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Stir-fried beef & chinese broccoli")
Item.create(name: "CHINESE MUSTARD WITH TOFU", smallT: 27, mediumT: 50, largeT: 95, smallC: 3, mediumC: 5.5, largeC: 11, dish: "Vegetable", desc: "Mushrooms, tofu w/ chinese mustard greens")
Item.create(name: "CHOPSUEY", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 12, dish: "Vegetable")
Item.create(name: "DININGDING", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 6, largeC: 12, dish: "Vegetable", desc: "Mixed vegetables w/ grilled fish")
Item.create(name: "EGGPLANT WITH SPICY SAUCE", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 12, dish: "Vegetable")
Item.create(name: "GINATAANG LANGKA", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Green jackfruit w/ coconut milk")
Item.create(name: "GINISANG MONGO", smallT: 25, mediumT: 45, largeT: 85, smallC: 3, mediumC: 5.5, largeC: 11, dish: "Vegetable", desc: "Sauteed mung bean w/ pork & shrimp")
Item.create(name: "GINISANG PATOLA", smallT: 27, mediumT: 50, largeT: 95, smallC: 3, mediumC: 5.5, largeC: 11, dish: "Vegetable", desc: "Sauteed Sinqua")
Item.create(name: "GINISANG PECHAYorMUSTAorBOKC", smallT: 27, mediumT: 50, largeT: 95, smallC: 3, mediumC: 5.5, largeC: 11, dish: "Vegetable", desc: "Sauteed choy sum, green mustard, or bokchoy")
Item.create(name: "GINISANG TALONG", smallT: 27, mediumT: 50, largeT: 95, smallC: 3, mediumC: 5.5, largeC: 11, dish: "Vegetable", desc: "Sauteed eggplant")
Item.create(name: "GINISANG TOGE", smallT: 27, mediumT: 50, largeT: 95, smallC: 3, mediumC: 5.5, largeC: 11, dish: "Vegetable", desc: "Sauteed bean sprout w/ tofu & shrimp")
Item.create(name: "GINISANG SITAW", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Sauteed long beans")
Item.create(name: "GINATAANG SITAW WITH SHRIMP", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Long beans w/ shrimp & coconut milk")
Item.create(name: "GINATAANG SITAW WITH CRAB", smallT: 30, mediumT: 55, largeT: 105, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Long beans w/ crabs & coconut milk")
Item.create(name: "GREEN PEAS WITH CASHEW & SHRIMP", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Sauteed shrimp & vegetables")
Item.create(name: "KILAWING PUSO NG SAGING", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Sauteed banana blossom in vinegar")
Item.create(name: "LAING", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Taro leaves w/ coconut milk")
Item.create(name: "MIXED VEGETABLE WITH SHRIMP AND QUAIL EGGS", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 12, dish: "Vegetable")
Item.create(name: "PINAKBET", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 12, dish: "Vegetable", desc: "Mixed vegetables w/ shrimp paste & pork")
Item.create(name: "SITAW WITH BEEF TAUSI", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Long beans w/ black beans")
Item.create(name: "VEGETABLE BICOL EXPRESS", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable", desc: "Mixed tropical vegetables w/ coconut milk")
Item.create(name: "VEGETABLE WITH PORK & TOFU", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 12, dish: "Vegetable", desc:"Sauteed vegetables w/ pork & tofu")
Item.create(name: "ZUCCHINI WITH SHRIMP & QUAIL EGGS", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Vegetable")

# Pork
Item.create(name: "PORK ADOBO", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Pork", desc:"Pork marinated in adobo sauce w/ garlic")
Item.create(name: "PORK AFRITADA", smallT: 27, mediumT: 50, largeT: 95,  smallC: 3.5, mediumC: 6, largeC: 11, dish: "Pork", desc:"Stewed pork w/ potato, carrots, pepper")
Item.create(name: "PORK ASADO", smallT: 30, mediumT: 55, largeT: 105,  smallC: 3.5, mediumC: 6, largeC: 12, dish: "Pork", desc:"Braised dish made out of marinated pork with a sweet tangy sauce")
Item.create(name: "PORK BBQ ON STICK", misc: "MARKET PRICE", dish: "Pork", desc:"Marinated and grilled pork cubes")
Item.create(name: "PORK BICOL EXPRESS", smallT: 30, mediumT: 55, largeT: 105,  smallC: 3.5, mediumC: 7, largeC: 14, dish: "Pork", desc:"Diced pork w/ coconut milk")
Item.create(name: "PORK BINAGOONGAN", smallT: 30, mediumT: 55, largeT: 105,  smallC: 3.5, mediumC: 6.5, largeC: 12, dish: "Pork", desc:"Pork chunks in shrimp fry & fried eggplant")
Item.create(name: "PORK EMBOTIDO", each: 6.5, dish: "Pork", desc:"Pork meatloaf")
Item.create(name: "PORK HIGADO", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 12, dish: "Pork", desc:"Pork, liver, greenpeas, red & green pepper")
Item.create(name: "PORK GINILING", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 6.5, largeC: 12, dish: "Pork", desc:"Ground pork mixed w/ carrots, potato, and quail eggs")
Item.create(name: "PORK KINAMATISAN", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 12, dish: "Pork", desc:"Pork sauteed in tomato")
Item.create(name: "PORK MEAT BALLS", mediumT: 55, largeT: 105, mediumC: 6, largeC: 12, dish: "Pork", desc:"Sweet & sour pork meatballs")
Item.create(name: "PORK MENUDO", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Pork", desc:"Diced pork, liver, hotdog, potato, carrots")
Item.create(name: "PORK NILAGA", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Pork", desc:"Pork soup w/ vegetables")
Item.create(name: "PORK POCHERO", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Pork", desc:"Pork stew w/ garbanzos, carrots, sweet potato, and plantain")
Item.create(name: "PORK SINIGANG", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Pork", desc:"Pork soup w/ tamarind flavor and tropical vegetables")
Item.create(name: "BOPIS", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Pork", desc:"Mixed pork meat, snout, tomato")
Item.create(name: "CRISPY PATA", misc: "BASED ON SIZE", dish: "Pork", desc:"Fried pork hock")
Item.create(name: "DINUGUAN", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Pork", desc:"Diced pork stewed in pork blood")
Item.create(name: "FRIED PORK CHOP", misc: "BASED ON SIZE", dish: "Pork", desc:"Fried breaded pork chop")
Item.create(name: "FRIED PORK RIBS", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 6, largeC: 12, dish: "Pork", desc:"Marinated fried pork ribs")
Item.create(name: "INIHAW NA LIEMPO", misc: "BASED ON SIZE", dish: "Pork", desc:"Grilled pork belly")
Item.create(name: "KIKIAM (PORK)", each: 3.5, dish: "Pork", desc:"Diced pork sausage")
Item.create(name: "KILAWING PORK WITH TOKWA", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Pork", desc:"Grilled pork, snout, and tofu w/ side of vinegat sauce")
Item.create(name: "LECHON KAWALI (PER POUND)", each: 15, dish: "Pork", desc:"Fried pork belly")
Item.create(name: "LECHON PAKSIW", smallT: 42, mediumT: 80, largeT: 155, smallC: 4.5, mediumC: 8, largeC: 16, dish: "Pork", desc:"Stewed roasted pig")
Item.create(name: "PAKSIW NA PATA", smallT: 27, mediumT: 50, largeT: 95, mediumC: 6, largeC: 11, dish: "Pork", desc:"Stewed pork hock")
Item.create(name: "SISIG LECHON KAWALI", smallT: 37, mediumT: 70, largeT: 135, smallC: 4.5, mediumC: 7, largeC: 14, dish: "Pork", desc:"Crispy fried pork w/ sweet tangy sauce")
Item.create(name: "SISIG ORIGINAL", mediumT: 70, largeT: 135, smallC: 4.5, mediumC: 7, largeC: 14, dish: "Pork", desc:"Grilled and chopped pork snout, ears, and neck w/ spices")
Item.create(name: "SIZZLING PORK", smallT: 42, mediumT: 80, largeT: 155, smallC: 4, mediumC: 7, largeC: 14, dish: "Pork", desc:"Spiced strips of pork shoulder fried crisp")
Item.create(name: "SWEET & SOUR PORK", smallT: 27, mediumT: 50, largeT: 95, smallC: 3.5, mediumC: 6, largeC: 12, dish: "Pork")

# Noodle
Item.create(name: "BIHON GUISADO", smallT: 20, mediumT: 38, largeT: 75, smallC: 2, mediumC: 4, largeC: 8, dish: "Noodle", desc:"Rice noodles, meat, & veggies")
Item.create(name: "CANTON GUISADO", smallT: 20, mediumT: 38, largeT: 75, smallC: 2, mediumC: 4, largeC: 8, dish: "Noodle", desc:"Wheat noodles, meat, & veggies")
Item.create(name: "LOMI", smallT: 25, mediumT: 45, largeT: 85, mediumC: 5, largeC: 10, dish: "Noodle", desc:"Round thick egg noodles")
Item.create(name: "MIKI/BIHON GUISADO", smallT: 20, mediumT: 38, largeT: 75, smallC: 2, mediumC: 4, largeC: 8, dish: "Noodle", desc:"Stir-fry noodles w/ meat & veggies")
Item.create(name: "MIKI GUISADO", smallT: 20, mediumT: 38, largeT: 75, smallC: 2, mediumC: 4, largeC: 8, dish: "Noodle", desc:"Stir-fry noodle w/ meat & veggies")
Item.create(name: "PALABOK", smallT: 25, mediumT: 45, largeT: 85, smallC: 2.5, mediumC: 5, largeC: 10, dish: "Noodle", desc:"Stir-fried seafood noddle dish")
Item.create(name: "PALABOK (THIN NOODLES)", smallT: 25, mediumT: 45, largeT: 85, smallC: 2.5, mediumC: 5, largeC: 10, dish: "Noodle", desc:"Noodles sauteed w/ meat and mixed veggies")
Item.create(name: "SOTANGHON GUISADO", smallT: 20, mediumT: 38, largeT: 75, smallC: 2, mediumC: 4, largeC: 8, dish: "Noodle", desc:"Vermicelli noodle sauteed")
Item.create(name: "SOTANGHON SOUP WITH CHICKEN", smallT: 20, mediumT: 38, largeT: 75, mediumC: 5, largeC: 10, dish: "Noodle", desc:"Vermicelli noodle dish w/ chix soup")
Item.create(name: "SPAGHETTI", smallT: 27, mediumT: 48, largeT: 90, smallC: 2.5, mediumC: 5, largeC: 10, dish: "Noodle", desc:"Filipino style spaghetti")
Item.create(name: "STEAMED MISUA", smallT: 20, mediumT: 38, largeT: 75, mediumC: 5, largeC: 10, dish: "Noodle", desc:"Steamed misua w/ pork, meatballs, and fishballs")

# Beef
Item.create(name: "BEEF ADOBO", smallT: 32, mediumT: 60, largeT: 115, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Beef adobo w/ eggs")
Item.create(name: "BEEF AFRITADA", smallT: 30, mediumT: 55, largeT: 105, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Beef stewed in tomato sauce")
Item.create(name: "BEEF ASADO", smallT: 32, mediumT: 60, largeT: 115, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"slow cooked beef & spices")
Item.create(name: "BEEF STEAK", smallT: 30, mediumT: 55, largeT: 105, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Beef sliced thin & marinated topped with onions")
Item.create(name: "BEEF CALLOS", smallT: 30, mediumT: 55, largeT: 105, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Tender beef tripe & knuckles")
Item.create(name: "BEEF CALDERETA", smallT: 30, mediumT: 55, largeT: 105, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Sweet & savory beef stew")
Item.create(name: "BEEF STEW WITH LABANOS", smallT: 30, mediumT: 55, largeT: 105, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Chinese style braised beef w/ radish")
Item.create(name: "BEEF PAPAITAN", smallT: 32, mediumT: 60, largeT: 115, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Beef innards w/ bitter bile")
Item.create(name: "BEEF PEPPER STEAK", smallT: 32, mediumT: 60, largeT: 115, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Beef steak w/ bell peppers")
Item.create(name: "BEEF POCHERO", smallT: 30, mediumT: 55, largeT: 105, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Stewed beefmeat w/ tomato")
Item.create(name: "BEEF SINIGANG", smallT: 30, mediumT: 55, largeT: 105, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Beef & veggies in sour tamarind soup")
Item.create(name: "FRIED BEEF RIBS", smallT: 32, mediumT: 60, largeT: 115, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Marinated fried beef ribs")
Item.create(name: "KARE KARE OX-TAIL", smallT: 30, mediumT: 55, largeT: 105, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Beef ox tail in peanut braised sauce")
Item.create(name: "KOREAN BBQ", misc: "BASED ON SIZE", dish: "Beef", desc:"Tasty & tender grilled beef")
Item.create(name: "LENGUA WITH CREAM SAUCE", smallT: 32, mediumT: 60, largeT: 115, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Ox tongue in creamy mushroom sauce with potatoes and carrots")
Item.create(name: "LENGUA WITH TOMATO SAUCE", smallT: 32, mediumT: 60, largeT: 115, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Ox tongue in tomato sauce")
Item.create(name: "NILAGANG BULALO", smallT: 30, mediumT: 55, largeT: 105, smallC: 4, mediumC: 7.5, largeC: 14, dish: "Beef", desc:"Beef stew w/ shanks & marrow")
Item.create(name: "ROAST BEEF", mediumT: 80, largeT: 155, smallC: 4.5, mediumC: 9, largeC: 18, dish: "Beef", desc:"Beef slowly roasted in oven w/ mushroom sauce")

# Chicken
Item.create(name: "CHICKEN ADOBO", smallT: 25, mediumT: 45, largeT: 85, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Chicken", desc:"Chicken marinated in adobo sauce w/ garlice")
Item.create(name: "CHICKEN AFRITADA", smallT: 25, mediumT: 45, largeT: 85, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Chicken", desc:"Chicken in tomato sauce")
Item.create(name: "CHICKEN BBQ LEGS", misc: "BASED ON SIZE", dish: "Chicken", desc:"Grilled marinated checken leg quarters")
Item.create(name: "CHICKEN BBQ ON STICK", misc: "MARKET PRICE", dish: "Chicken", desc:"Grilled marinated chicken")
Item.create(name: "CHICKEN CURRY", smallT: 25, mediumT: 45, largeT: 85, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Chicken", desc:"Chicken sauteed curry sauce")
Item.create(name: "CHICKEN EMBOTIDO", each: 6.5, dish: "Chicken", desc:"Meatloaf of ground chicken")
Item.create(name: "CHICKEN EMPANADA", misc: "MARKET PRICE", dish: "Chicken", desc:"Chicken stuffed pie")
Item.create(name: "CHICKEN FILET WITH MUSHROOM", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Chicken", desc:"Chicken w/ creamy mushroom")
Item.create(name: "FRIED CHICKEN LEG & THIGH (REGULAR)", each: 3.5, dish: "Chicken", desc:"Marinated and fried chicken")
Item.create(name: "FRIED CHICKEN LEG & THIGH (SAVORY)", each: 3.5, dish: "Chicken", desc:"Chinese style fried chicken")
Item.create(name: "CHICKEN LOLLIPOP", mediumT: 55, largeT: 105, dish: "Chicken", desc:"Red garlic, chile, & soy fried chicken wings in the form of a lollipop")
Item.create(name: "CHICKEN NILAGA", smallT: 25, mediumT: 45, largeT: 85, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Chicken", desc:"Boiled chicken soup")
Item.create(name: "KIKIAM (CHICKEN)", each: 3.5, dish: "Chicken", desc:"Ground chicken & vegetables formed into a sausage")
Item.create(name: "ORANGE CHICKEN", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Chicken", desc:"Deep fried battered chicken in sweet & sour sauce")
Item.create(name: "CHICKEN PASTEL", smallT: 25, mediumT: 45, largeT: 85, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Chicken", desc:"Creamy chicken dish encased in pie crust")
Item.create(name: "PINEAPPLE CHICKEN", smallT: 25, mediumT: 45, largeT: 85, smallC: 3.5, mediumC: 6, largeC: 11, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Chicken", desc:"Sweet & sour chicken lightly sweetened w/ honey")
Item.create(name: "CHICKEN POCHERO", smallT: 25, mediumT: 45, largeT: 85, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Chicken", desc:"Chicken stewed w/ vegetables, plantain, & tomato")
Item.create(name: "CHICKEN SINAMPALUKAN", smallT: 25, mediumT: 45, largeT: 85, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Chicken", desc:"Chicken, vegetables, and tamarind leaves")
Item.create(name: "SPICY CHICKEN WINGS", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 6, largeC: 12, dish: "Chicken", desc:"Spicy buffalo chicken wings")
Item.create(name: "CHICKEN TINOLA", smallT: 25, mediumT: 45, largeT: 85, smallC: 3.5, mediumC: 6, largeC: 11, dish: "Chicken", desc:"Chicken ginger stew")
Item.create(name: "SWEET & SOUR CHICKEN FILLET", smallT: 30, mediumT: 55, largeT: 105, smallC: 3.5, mediumC: 7, largeC: 14, dish: "Chicken", desc:"Pan-fried chicken in sweet & sour sauce")
Item.create(name: "CHICKEN TERIYAKI FILLET", smallT: 30, mediumT: 55, largeT: 105, smallC: 4, mediumC: 7, largeC: 14, dish: "Chicken", desc:"Grilled marinated chicken w/ teriyaki sauce")

# Seafood (squid)
Item.create(name: "ADOBONG PUSIT", smallT: 32, mediumT: 60, largeT: 115, dish:"Seafood(SQUID)")
Item.create(name: "CALAMARI", smallT: 35, mediumT: 65, largeT: 130, dish:"Seafood(SQUID)")
Item.create(name: "INIHAW NA PUSIT(Jumbo)", misc: "MARKET PRICE", dish:"Seafood(SQUID)")
Item.create(name: "KILAWING TUNA", smallT: 38, mediumT: 75, largeT: 150, dish:"Seafood(SQUID)")
Item.create(name: "KILAWING ALBACORE", smallT: 38, mediumT: 75, largeT: 150, dish:"Seafood(SQUID)")

# Seafood (fish)
Item.create(name: "FRIED MILKFISH(DAING)", each: 8, dish:"Seafood(FISH)")
Item.create(name: "ESCABECHE", misc: "BASED ON AVAILABILITY", dish:"Seafood(FISH)")
Item.create(name: "FISH FILLET WITH TOFU", smallT: 32, mediumT: 60, largeT: 115, dish:"Seafood(FISH)")
Item.create(name: "FISH STEAK BANGUS", mediumT: 10, dish:"Seafood(FISH)")
Item.create(name: "FRIED JEPROX", smallT: 22, mediumT: 40,largeT: 80, dish:"Seafood(FISH)")
Item.create(name: "FRIED SMELT(DILIS)", smallT: 22, mediumT: 40, largeT: 80, dish:"Seafood(FISH)")
Item.create(name: "FRIED SMELT(REGULAR)", misc: "PER LB", dish:"Seafood(FISH)")
Item.create(name: "GINATAANG ISDA", misc: "BASED ON AVAILABILITY", dish:"Seafood(FISH)")
Item.create(name: "MIXED SEAFOODS", smallT: 32, mediumT: 60,largeT: 115, dish:"Seafood(FISH)")
Item.create(name: "PINANGAT SA KAMIAS", misc: "BASED ON AVAILABILITY", dish:"Seafood(FISH)")
Item.create(name: "PINANGAT SA SAMPALOK", misc: "BASED ON AVAILABILITY", dish:"Seafood(FISH)")
Item.create(name: "RELLENONG BANGUS", each: 16, dish:"Seafood(FISH)")
Item.create(name: "SARCIADO", misc: "BASED ON AVAILABILITY", dish:"Seafood(FISH)")
Item.create(name: "SINIGANG SA BAYABAS", misc: "BASED ON AVAILABILITY", dish:"Seafood(FISH)")
Item.create(name: "SINIGANG SA KAMIAS", misc: "BASED ON AVAILABILITY", dish:"Seafood(FISH)")
Item.create(name: "SINIGANG SAA SAMPALOK", misc: "BASED ON AVAILABILITY", dish:"Seafood(FISH)")
Item.create(name: "SWEET AND SOUR FISH", misc: "BASED ON AVAILABILITY", dish:"Seafood(FISH)")
Item.create(name: "TAUSI", misc: "BASED ON AVAILABILITY", dish:"Seafood(FISH)")
Item.create(name: "TO-CHO", misc: "BASED ON AVAILABILITY", dish:"Seafood(FISH)")
Item.create(name: "SWEET & SOUR FISH FILLET", smallT: 32, mediumT: 60,largeT: 115, dish:"Seafood(FISH)")

# Seafood (shrimp & kuhol)
Item.create(name: "CAMARON REBUSADO", smallT: 38, mediumT:75, largeT: 150, dish:"Seafood(SHRIMP & KUHOL)")
Item.create(name: "FRIED SHRIMP", smallT: 35, mediumT: 65, largeT: 130, dish:"Seafood(SHRIMP & KUHOL)")
Item.create(name: "FRIED TILAPIA", misc: "BASED ON SIZE 3-5", dish:"Seafood(SHRIMP & KUHOL)")
Item.create(name: "HALABOS NA HIPON", smallT: 35, mediumT: 65, largeT: 130, dish:"Seafood(SHRIMP & KUHOL)")
Item.create(name: "GINATAANG NA KUHOL", smallT: 38, mediumT: 75, largeT: 150, dish:"Seafood(SHRIMP & KUHOL)")
Item.create(name: "KILAWING AN HIPON", smallT: 35, mediumT: 65, largeT: 130, dish:"Seafood(SHRIMP & KUHOL)")
Item.create(name: "SINIGANG NA HIPON", smallT: 30, mediumT: 55, largeT: 105, dish:"Seafood(SHRIMP & KUHOL)")
Item.create(name: "SWEET & SOUR SHRIMP", smallT: 35, mediumT: 65, largeT: 130, dish:"Seafood(SHRIMP & KUHOL)")

# Kambing
Item.create(name: "KALDERETANG KAMBING", smallT: 38, mediumT: 75, largeT: 150, dish:"Kambing")
Item.create(name: "KILAWING KAMBING", smallT: 40, mediumT: 80, largeT: 160, dish:"Kambing")

# PerPiece Or Pound
Item.create(name: "CHICKEN BBQ LEGS", misc: "BASED ON SIZE", dish: "Per Piece or Pound")
Item.create(name: "CHICHARON BULAKLAK", misc: "MARKETPRICE", dish: "Per Piece or Pound")
Item.create(name: "CRISPY PATA", misc: "BASED ON SIZE", dish: "Per Piece or Pound")
Item.create(name: "DAING NA BUNGUS", each: 8, dish: "Per Piece or Pound")
Item.create(name: "PORK EMBOTIDO",each: 6.50, dish: "Per Piece or Pound")
Item.create(name: "CHICKEN EMBOTIDO", each: 6.50, dish: "Per Piece or Pound")
Item.create(name: "CHICKEN EMPANADA", misc: "MARKETPRICE", dish: "Per Piece or Pound")
Item.create(name: "FRIED PORLCHOP", misc: "BASED ON SIZE", dish: "Per Piece or Pound")
Item.create(name: "INIHAW NA BANGUS", each: 8, dish: "Per Piece or Pound")
Item.create(name: "INIHAW NA LIEMPO", misc: "BASED ON SIZE", dish: "Per Piece or Pound")
Item.create(name: "INIHAW NA POMPANO", misc: "BASED ON SIZE", dish: "Per Piece or Pound")
Item.create(name: "INIHAW NA TILAPIA", misc: "BASED ON SIZE", dish: "Per Piece or Pound")
Item.create(name: "CHICKEN KIKIAM", each: 3.50, dish: "Per Piece or Pound")
Item.create(name: "PORK KIKIAM", each: 3.50, dish: "Per Piece or Pound")
Item.create(name: "KOREAN BBQ", misc: "BASED ON SIZE", dish: "Per Piece or Pound")
Item.create(name: "MORCON(Seasonal)", misc: "MARKETPRICE", dish: "Per Piece or Pound")
Item.create(name: "OKOY WITH TOGE", each: 3.50, dish: "Per Piece or Pound")
Item.create(name: "OKOY WITH DULONG", misc: "BASED ON AVAILABILITY", dish: "Per Piece or Pound")
Item.create(name: "CHICKEN BBQ ON STICK", misc: "MARKETPRICE", dish: "Per Piece or Pound")
Item.create(name: "PORK BBQ ON STICK", misc: "MARKETPRICE", dish: "Per Piece or Pound")
Item.create(name: "RELLENONG BANGUS", each: 16, dish: "Per Piece or Pound")
Item.create(name: "TORTANG TALONG(with meat)", each: 3, dish:"Per Piece or Pound")
Item.create(name: "TORTANG TALONG(no meat)", each: 2.50, dish:"Per Piece or Pound")

# Lumpipang Shanghai
Item.create(name: "PORK SHANGHAI", smallT: 22, mediumT: 44, largeT: 63, dish: "Lumpiang Shanghai")
Item.create(name: "VEGETABLE SHANGHAI", smallT: 20, mediumT: 40, largeT: 57, dish: "Lumpiang Shanghai")
Item.create(name: "BEEF SHANGHAI", smallT: 22, mediumT: 44, largeT: 63, dish: "Lumpiang Shanghai")
Item.create(name: "CHICKEN SHANGHAI", smallT: 22, mediumT: 44, largeT: 63, dish: "Lumpiang Shanghai")

# Lumpia (chinese ubod vegetables)
Item.create(name: "FRESH CHINESE", each: 2, dish: "Lumpia (Chinese-Ubod-Vegetables)")
Item.create(name: "FRESH UBOD", each: 2, dish: "Lumpia (Chinese-Ubod-Vegetables)")
Item.create(name: "FRIED REGULAR LUMPIA(TOGE)", each: 1, dish: "Lumpia (Chinese-Ubod-Vegetables)")
Item.create(name: "FRIED UBOD", each: 1.50, dish: "Lumpia (Chinese-Ubod-Vegetables)")

# Rice
Item.create(name: "GARLIC FRIED RICE", smallT: 13, mediumT: 25, largeT: 50, dish:"Rice")
Item.create(name: "SHRIMP FRIED RICE", smallT: 15, mediumT: 27, largeT: 55, dish:"Rice")
Item.create(name: "STEAMED RICE (regular)", smallT: 8, mediumT: 16, largeT: 32, dish:"Rice")

# Lechon (Roast Pig)
Item.create(name: "LECHON (ROAST-PIG)", half: 185, whole: 285, dish: "Lechon (Roast-Pig)")
Item.create(name: "LECHON (ROAST-PIG)", misc: "18 per lb", dish: "Lechon (Roast-Pig)")

# Desserts 
# Comes In (serving tray)
Item.create(name: "ASSORTED KAKANIN", full: 35, dish: "Desserts")
Item.create(name: "BIKO w/ COCOJAM", half: 18, full: 28, dish: "Desserts")
Item.create(name: "BIKO w/ LATIK", half: 18, full: 28, dish: "Desserts")
Item.create(name: "UBE BIKO", half: 18, full: 28, dish: "Desserts")
Item.create(name: "CASSAVA w/ MACAPUNO", half: 19, full: 30, dish: "Desserts")
Item.create(name: "CASSAVA w/ FLAN", half: 20, full: 35, dish: "Desserts")
Item.create(name: "NILUPAK", half: 25, full: 34, dish: "Desserts")

# Comes In (round trays)
Item.create(name: "KUTSINTA", smallT: 14.50, largeT: 25.50, dish: "Desserts")
Item.create(name: "PALITAW (Seasonal)", smallT: 15, largeT: 28.50, dish: "Desserts")
Item.create(name: "PICHI PICHI w/ CHEESE", smallT: 23, dish: "Desserts")
Item.create(name: "PICHI PICHI w/ COCONUT", smallT: 23, dish: "Desserts")
Item.create(name: "PUTO BUMBONG (Seasonal)", smallT: 30, largeT: 60, dish: "Desserts")
Item.create(name: "RAINBOW PUTO", smallT: 14.50, largeT: 25.50, dish: "Desserts")
Item.create(name: "PUTONG PUTI", smallT: 14.50, largeT: 25.50, dish: "Desserts")
Item.create(name: "PUTO w/ CHEESE", smallT: 22.50, largeT: 43.50, dish: "Desserts")
Item.create(name: "PUTO w/ SALTED EGG", smallT: 22.50, largeT: 43.50, dish: "Desserts")

# per piece
Item.create(name: "BANANA-QUE", misc: "BASED ON SIZE", dish: "Desserts per Piece")
Item.create(name: "KAMOTE-QUE", misc: "BASED ON SIZE", dish: "Desserts per Piece")
Item.create(name: "LECHE FLAN", each: 6.89, dish: "Desserts per Piece")
Item.create(name: "TAHO", each: 3.50, dish: "Desserts per Piece")
Item.create(name: "TURON (Saging)", misc: "MARKETPRICE", dish: "Desserts per Piece")
Item.create(name: "TURONITOS (mini turon)", misc: "BASED ON AVAILABILITY", dish: "Desserts per Piece")
Item.create(name: "SUMAN SA ANTALA(2 Pieces)", each: 1, dish: "Desserts per Piece")
Item.create(name: "SUMAN SA CASSAVA (2 Pieces)", each: 1, dish: "Desserts per Piece")
Item.create(name: "SUMAN SA UBE (2 Pieces)", each: 1, dish: "Desserts per Piece")
Item.create(name: "UBE HALAYA (extra smallT tray)", each: 7, dish: "Desserts per Piece")

# sml md lrg attributes
Item.create(name: "BUKO PANDAN", smallT: 20, mediumT: 37, largeT: 70, dish: "Desserts")
Item.create(name: "GINATAANG NA HALO HALO", smallT: 18, mediumT: 35, largeT: 70, dish: "Desserts")
Item.create(name: "GINATAANG NA MAIS", smallT: 15, mediumT: 30, largeT: 60, dish: "Desserts")









