# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Item.destroy_all

Item.create(name: "ADOBONG KANGKONG", misc: "MARKET PRICE", dish: "Vegetable")
Item.create(name: "ADOBONG SITAW", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "AMPALAYA CON KARNE", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "AMPALAYA WITH EGG & SHRIMP", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "ASPARAGUS WITH SHRIMP", small: 30, medium: 55, large: 105, dish: "Vegetable")
Item.create(name: "BROCCOLI WITH BEEF", small: 30, medium: 55, large: 105, dish: "Vegetable")
Item.create(name: "CHINESE BROCCOLI WITH BEEF", small: 30, medium: 55, large: 105, dish: "Vegetable")
Item.create(name: "CHINESE MUSTARD WITH TOFU", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "CHOPSUEY", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "DININGDING", small: 30, medium: 55, large: 105, dish: "Vegetable")
Item.create(name: "EGGPLANT WITH SPICY SAUCE", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "GINATAANG LANGKA", small: 30, medium: 55, large: 105, dish: "Vegetable")
Item.create(name: "GINISANG MONGO", small: 25, medium: 45, large: 85, dish: "Vegetable")
Item.create(name: "GINISANG PATOLA", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "GINISANG PECHAYorMUSTAorBOKC", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "GINISANG TALONG", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "GINISANG TOGE", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "GINISANG SITAW", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "GINATAANG SITAW WITH SHRIMP & CRAB", small: 30, medium: 55, large: 105, dish: "Vegetable")
Item.create(name: "GREEN PEAS WITH CASHEW & SHRIMP", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "KILAWING PUSO NG SAGING", small: 30, medium: 55, large: 105, dish: "Vegetable")
Item.create(name: "LAING", small: 30, medium: 55, large: 105, dish: "Vegetable")
Item.create(name: "MIXED VEGETABLE WITH SHRIMP AND QUAIL EGGS", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "PINAKBET", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "SITAW WITH BEEF TAUSI", small: 30, medium: 55, large: 105, dish: "Vegetable")
Item.create(name: "VEGETABLE BICOL EXPRESS", small: 30, medium: 55, large: 105, dish: "Vegetable")
Item.create(name: "VEGETABLE WITH PORK & TOFU", small: 27, medium: 50, large: 95, dish: "Vegetable")
Item.create(name: "ZUCCHINI WITH SHRIMP & QUAIL EGGS", small: 30, medium: 55, large: 105, dish: "Vegetable")
Item.create(name: "PORK ADOBO", small: 27, medium: 50, large: 95, dish: "Pork")
Item.create(name: "PORK AFRITADA", small: 27, medium: 50, large: 95, dish: "Pork")
Item.create(name: "PORK ASADO", small: 30, medium: 55, large: 105, dish: "Pork")
Item.create(name: "PORK BBQ ON STICK", misc: "MARKET PRICE", dish: "Pork")
Item.create(name: "PORK BICOL EXPRESS", small: 30, medium: 55, large: 105, dish: "Pork")
Item.create(name: "PORK BINAGOONGAN", small: 30, medium: 55, large: 105, dish: "Pork")
Item.create(name: "PORK EMBOTIDO", each: 6.5, dish: "Pork")
Item.create(name: "PORK HIGADO", small: 27, medium: 50, large: 95, dish: "Pork")
Item.create(name: "PORK GINILING", small: 30, medium: 55, large: 105, dish: "Pork")
Item.create(name: "PORK KINAMATISAN", small: 27, medium: 50, large: 95, dish: "Pork")
Item.create(name: "PORK MEAT BALLS", medium: 55, large: 105, dish: "Pork")
Item.create(name: "PORK MENUDO", small: 27, medium: 50, large: 95, dish: "Pork")
Item.create(name: "PORK NILAGA", small: 27, medium: 50, large: 95, dish: "Pork")
Item.create(name: "PORK POCHERO", small: 30, medium: 55, large: 105, dish: "Pork")
Item.create(name: "PORK SINIGANG", small: 27, medium: 50, large: 95, dish: "Pork")
Item.create(name: "BOPIS", small: 30, medium: 55, large: 105, dish: "Pork")
Item.create(name: "CRISPY PATA", misc: "BASED ON SIZE", dish: "Pork")
Item.create(name: "DINUGUAN", small: 27, medium: 50, large: 95, dish: "Pork")
Item.create(name: "FRIED PORK CHOP", misc: "BASED ON SIZE", dish: "Pork")
Item.create(name: "FRIED PORK RIBS", small: 30, medium: 55, large: 105, dish: "Pork")
Item.create(name: "INIHAW NA LEIMPO", misc: "BASED ON SIZE", dish: "Pork")
Item.create(name: "KIKIAM (PORK)", each: 3.5, dish: "Pork")
Item.create(name: "KILAWING PORK WITH TOKWA", small: 27, medium: 50, large: 95, dish: "Pork")
Item.create(name: "LECHON KAWALI (PER POUND)", each: 15, dish: "Pork")
Item.create(name: "LECHON PAKSIW", small: 42, medium: 80, large: 155, dish: "Pork")
Item.create(name: "PAKSIW NA PATA", small: 27, medium: 50, large: 95, dish: "Pork")
Item.create(name: "SISIG LECHON KAWALI", small: 37, medium: 70, large: 135, dish: "Pork")
Item.create(name: "SISIG ORIGINAL", medium: 70, large: 135, dish: "Pork")
Item.create(name: "SIZZLING PORK", small: 42, medium: 80, large: 155, dish: "Pork")
Item.create(name: "SWEET & SOUR PORK", small: 27, medium: 50, large: 95, dish: "Pork")




